/**
 * Daily digest generation and delivery for Argus.
 *
 * Orchestrates:
 *   1. Collect stats from the last 24h
 *   2. Render Slack Block Kit payload and HTML report
 *   3. Deliver to configured channels (Slack webhook, email)
 *   4. Save a local HTML file to ~/.argus/
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { getAllEvents24h, getNotificationConfig } from '../db/queries.js';
import { renderHtmlReport } from './digest-html.js';
import { config } from './config.js';

// ─── Data collection ──────────────────────────────────────────────────────────

/**
 * Gather all stats needed for the daily digest.
 *
 * @param {import('better-sqlite3').Database} db
 * @returns {{
 *   date: string,
 *   processCount: number,
 *   fileAlertCount: number,
 *   networkEventCount: number,
 *   topFiles: { file_path: string, access_count: number }[],
 *   topEndpoints: { remote_host: string, connection_count: number }[],
 *   alerts: object[],
 *   aiServices: string[]
 * }}
 */
export async function generateDigestData(db) {
  const { fileAlerts, networkEvents, processCount, topFiles, topEndpoints } =
    getAllEvents24h(db);

  const aiServiceSet = new Set(
    networkEvents
      .map((e) => e.ai_service)
      .filter(Boolean)
  );

  return {
    date: new Date().toISOString().slice(0, 10),
    processCount,
    fileAlertCount: fileAlerts.length,
    networkEventCount: networkEvents.length,
    topFiles,
    topEndpoints,
    alerts: fileAlerts,
    aiServices: [...aiServiceSet],
  };
}

// ─── Slack formatter ──────────────────────────────────────────────────────────

/**
 * Format digest data into a Slack Block Kit payload.
 *
 * @param {{
 *   date: string,
 *   processCount: number,
 *   fileAlertCount: number,
 *   networkEventCount: number,
 *   topFiles: object[],
 *   topEndpoints: object[],
 *   aiServices: string[]
 * }} data
 * @returns {object} Slack Block Kit payload (plain object)
 */
export function formatDigestForSlack(data) {
  const topFilesText = data.topFiles.length > 0
    ? data.topFiles
        .slice(0, 5)
        .map((f) => `• \`${f.file_path}\` — ${f.access_count} access${f.access_count !== 1 ? 'es' : ''}`)
        .join('\n')
    : '_No file accesses recorded._';

  const topEndpointsText = data.topEndpoints.length > 0
    ? data.topEndpoints
        .slice(0, 5)
        .map((e) => `• \`${e.remote_host}\` — ${e.connection_count} connection${e.connection_count !== 1 ? 's' : ''}`)
        .join('\n')
    : '_No network connections recorded._';

  const aiServicesText = data.aiServices.length > 0
    ? data.aiServices.join(', ')
    : 'None detected';

  return {
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `Argus Daily Digest — ${data.date}`,
          emoji: false,
        },
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Processes Seen*\n${data.processCount}`,
          },
          {
            type: 'mrkdwn',
            text: `*File Alerts*\n${data.fileAlertCount}`,
          },
          {
            type: 'mrkdwn',
            text: `*Network Events*\n${data.networkEventCount}`,
          },
          {
            type: 'mrkdwn',
            text: `*AI Services*\n${aiServicesText}`,
          },
        ],
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Top Files Accessed*\n${topFilesText}`,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Top Network Endpoints*\n${topEndpointsText}`,
        },
      },
      {
        type: 'divider',
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `Generated by Argus at ${new Date().toISOString()}`,
          },
        ],
      },
    ],
  };
}

// ─── Delivery channels ────────────────────────────────────────────────────────

/**
 * POST a Slack Block Kit payload to a webhook URL.
 *
 * @param {string} webhookUrl
 * @param {object} payload
 * @returns {Promise<{ success: boolean, error?: string }>}
 */
export async function sendSlackDigest(webhookUrl, payload) {
  try {
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const body = await response.text().catch(() => '');
      return {
        success: false,
        error: `Slack returned HTTP ${response.status}: ${body}`.slice(0, 200),
      };
    }

    return { success: true };
  } catch (err) {
    return { success: false, error: String(err?.message ?? err) };
  }
}

/**
 * Send the digest HTML via email using nodemailer.
 * Requires env vars: ARGUS_SMTP_HOST, ARGUS_SMTP_PORT, ARGUS_SMTP_USER, ARGUS_SMTP_PASS.
 *
 * @param {string} emailAddress
 * @param {{ subject: string, html: string }} opts
 * @returns {Promise<{ success: boolean, error?: string }>}
 */
export async function sendEmailDigest(emailAddress, { subject, html }) {
  const smtpHost = process.env.ARGUS_SMTP_HOST;
  const smtpPort = parseInt(process.env.ARGUS_SMTP_PORT || '587', 10);
  const smtpUser = process.env.ARGUS_SMTP_USER;
  const smtpPass = process.env.ARGUS_SMTP_PASS;

  if (!smtpHost || !smtpUser || !smtpPass) {
    return {
      success: false,
      error: 'SMTP not configured. Set ARGUS_SMTP_HOST, ARGUS_SMTP_USER, ARGUS_SMTP_PASS.',
    };
  }

  let nodemailer;
  try {
    nodemailer = (await import('nodemailer')).default;
  } catch {
    return {
      success: false,
      error: 'nodemailer is not installed. Run: npm install nodemailer',
    };
  }

  try {
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: { user: smtpUser, pass: smtpPass },
    });

    await transporter.sendMail({
      from: smtpUser,
      to: emailAddress,
      subject,
      html,
    });

    return { success: true };
  } catch (err) {
    return { success: false, error: String(err?.message ?? err) };
  }
}

// ─── Local file save ──────────────────────────────────────────────────────────

/**
 * Write the HTML digest to ~/.argus/digest-YYYY-MM-DD.html.
 *
 * @param {{ date: string }} data
 * @param {string} digestHtml
 * @returns {Promise<{ path: string }>}
 */
export async function saveLocalDigest(data, digestHtml) {
  const dir = config.DATA_DIR;
  mkdirSync(dir, { recursive: true, mode: 0o700 });

  const filename = `digest-${data.date}.html`;
  const filePath = join(dir, filename);

  writeFileSync(filePath, digestHtml, { encoding: 'utf8', mode: 0o600 });

  return { path: filePath };
}

// ─── Orchestrator ─────────────────────────────────────────────────────────────

/**
 * Run the full daily digest pipeline.
 * Generates data, renders HTML, sends to all configured channels, saves locally.
 *
 * @param {import('better-sqlite3').Database} db
 * @returns {Promise<{ sent: string[], saved: string }>}
 */
export async function runDailyDigest(db) {
  const data = await generateDigestData(db);

  const allEvents = [
    ...data.alerts.map((e) => ({ ...e, event_type: 'FILE' })),
  ];

  const digestHtml = renderHtmlReport({
    title: `Argus Daily Digest — ${data.date}`,
    summary: {
      processCount: data.processCount,
      fileAlertCount: data.fileAlertCount,
      networkEventCount: data.networkEventCount,
    },
    events: allEvents,
    generated: new Date().toISOString(),
  });

  const sent = [];

  // Slack
  const slackConfig = getNotificationConfig(db, 'slack');
  if (slackConfig?.target) {
    const payload = formatDigestForSlack(data);
    const result = await sendSlackDigest(slackConfig.target, payload);
    if (result.success) {
      sent.push('slack');
    } else {
      console.error(`[digest] Slack delivery failed: ${result.error}`);
    }
  }

  // Email
  const emailConfig = getNotificationConfig(db, 'email');
  if (emailConfig?.target) {
    const result = await sendEmailDigest(emailConfig.target, {
      subject: `Argus Daily Digest — ${data.date}`,
      html: digestHtml,
    });
    if (result.success) {
      sent.push('email');
    } else {
      console.error(`[digest] Email delivery failed: ${result.error}`);
    }
  }

  // Always save locally
  const { path: savedPath } = await saveLocalDigest(data, digestHtml);

  return { sent, saved: savedPath };
}
